services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=resumejobmatcher
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./src/backend
    volumes:
      - ./src/backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/resumejobmatcher
      - SECRET_KEY=your_super_secret_key_change_in_production
      - GEMINI_API_KEY=super_secret_key
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "python -c 'from app.db import init_db, seed_initial_data; init_db(); seed_initial_data()' && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    build: ./src/frontend
    volumes:
      - ./src/frontend:/app
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://backend:8000
    depends_on:
      - backend

volumes:
  postgres_data: 